version: '3'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - lead-automation-network

  # Frontend service (using Nginx)
  frontend:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - lead-automation-network
    depends_on:
      - backend

networks:
  lead-automation-network:
    driver: bridge
